# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 824)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        self.mainFrame.setStyleSheet("#mainFrame{\n"
                                     "background-color: rgba(56,57,60);\n"
                                     "border-radius:30px;\n"
                                     "}")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerFrame = QtWidgets.QFrame(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.headerFrame.sizePolicy().hasHeightForWidth())
        self.headerFrame.setSizePolicy(sizePolicy)
        self.headerFrame.setMinimumSize(QtCore.QSize(0, 70))
        self.headerFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.headerFrame.setStyleSheet("#headerFrame{\n"
                                       "background-color: rgba(70,130,180);\n"
                                       "border-top-left-radius:30px;\n"
                                       "border-top-right-radius:30px;\n"
                                       "}")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.logoFrame = QtWidgets.QFrame(self.headerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoFrame.sizePolicy().hasHeightForWidth())
        self.logoFrame.setSizePolicy(sizePolicy)
        self.logoFrame.setMinimumSize(QtCore.QSize(0, 70))
        self.logoFrame.setMaximumSize(QtCore.QSize(16777215, 55))
        self.logoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoFrame.setObjectName("logoFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.logoFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logoLabel = QtWidgets.QLabel(self.logoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setMinimumSize(QtCore.QSize(55, 55))
        self.logoLabel.setMaximumSize(QtCore.QSize(55, 55))
        self.logoLabel.setStyleSheet("border-image: url(../images/icon/logo.png);")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_3.addWidget(self.logoLabel, 0, QtCore.Qt.AlignTop)
        self.titleLabel = QtWidgets.QLabel(self.logoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 55))
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 55))
        self.titleLabel.setStyleSheet("QLabel#titleLabel{\n"
                                      "font: 20pt \"华文琥珀\";\n"
                                      "text-align: center;\n"
                                      "color:rgba(255,255,255);\n"
                                      "}")
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_3.addWidget(self.titleLabel, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_5.addWidget(self.logoFrame)
        spacerItem = QtWidgets.QSpacerItem(584, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.headerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minimizeButton = QtWidgets.QPushButton(self.frame)
        self.minimizeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.minimizeButton.setMaximumSize(QtCore.QSize(30, 30))
        self.minimizeButton.setStyleSheet("QPushButton#minimizeButton{\n"
                                          "border-image: url(../Images/icon/minwin.png);\n"
                                          "}\n"
                                          "QPushButton#minimizeButton:hover{\n"
                                          "border-image: url(../Images/icon/minwin1.png);\n"
                                          "}\n"
                                          "")
        self.minimizeButton.setText("")
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout.addWidget(self.minimizeButton)
        self.maxButton = QtWidgets.QPushButton(self.frame)
        self.maxButton.setMinimumSize(QtCore.QSize(30, 30))
        self.maxButton.setMaximumSize(QtCore.QSize(30, 30))
        self.maxButton.setStyleSheet("QPushButton#maxButton{\n"
                                     "border-image: url(../Images/icon/maxwin.png);\n"
                                     "}\n"
                                     "QPushButton#maxButton:hover{\n"
                                     "border-image: url(../Images/icon/maxwin1.png);\n"
                                     "}\n"
                                     "")
        self.maxButton.setText("")
        self.maxButton.setObjectName("maxButton")
        self.horizontalLayout.addWidget(self.maxButton)
        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.closeButton.setMaximumSize(QtCore.QSize(30, 30))
        self.closeButton.setStyleSheet("QPushButton#closeButton{\n"
                                       "border-image: url(../Images/icon/close.png);\n"
                                       "}\n"
                                       "QPushButton#closeButton:hover{\n"
                                       "border-image: url(../Images/icon/close1.png);\n"
                                       "}")
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.horizontalLayout_5.addWidget(self.frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.headerFrame)
        self.centerFrame = QtWidgets.QFrame(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerFrame.sizePolicy().hasHeightForWidth())
        self.centerFrame.setSizePolicy(sizePolicy)
        self.centerFrame.setStyleSheet("")
        self.centerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.centerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centerFrame.setObjectName("centerFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centerFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bodyFrame = QtWidgets.QFrame(self.centerFrame)
        self.bodyFrame.setStyleSheet("#bodyFrame{\n"
                                     "color:rgb(255,255,255);\n"
                                     "background-color: rgba(56,57,60);\n"
                                     "border-bottom-left-radius:30px;\n"
                                     "border-bottom-right-radius:30px;\n"
                                     "}")
        self.bodyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bodyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bodyFrame.setObjectName("bodyFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bodyFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.leftFrame = QtWidgets.QFrame(self.bodyFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftFrame.sizePolicy().hasHeightForWidth())
        self.leftFrame.setSizePolicy(sizePolicy)
        self.leftFrame.setMinimumSize(QtCore.QSize(150, 0))
        self.leftFrame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.leftFrame.setStyleSheet("QPushButton{\n"
                                     "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(102, 133, 156, 255), stop:1 rgba(117, 255, 201, 255));\n"
                                     "border:none;\n"
                                     "border-radius:7px;\n"
                                     "color:rgb(255,255,255);\n"
                                     "font: 9pt \"微软雅黑\";\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed{\n"
                                     "padding-left:5px;\n"
                                     "padding-top:5px;\n"
                                     "}\n"
                                     "#leftFrame{\n"
                                     "background-color: rgba(70,130,180);\n"
                                     "border-bottom-left-radius:30px;\n"
                                     "}")
        self.leftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolBox = QtWidgets.QToolBox(self.leftFrame)
        self.toolBox.setStyleSheet("QToolBoxButton {\n"
                                   "min-height: 50px; \n"
                                   "\n"
                                   "}\n"
                                   "\n"
                                   "QToolBox#toolBox::tab { \n"
                                   "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(102, 133, 156, 255), stop:1 rgba(117, 255, 201, 255));\n"
                                   "border:none;\n"
                                   "color:rgb(255,255,255);\n"
                                   "border-radius:7px;\n"
                                   "font: 13pt \"微软雅黑\";\n"
                                   "} \n"
                                   "\n"
                                   "\n"
                                   "QToolBox#toolBox::tab:selected { \n"
                                   "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(102, 133, 156, 255), stop:1 rgba(117, 255, 201, 255));\n"
                                   "border:none;\n"
                                   "border-radius:7px;\n"
                                   "color:rgb(255,255,255);\n"
                                   "} ")
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setObjectName("toolBox")
        self.scriptPage = QtWidgets.QWidget()
        self.scriptPage.setGeometry(QtCore.QRect(0, 0, 98, 84))
        self.scriptPage.setStyleSheet("#scriptPage{\n"
                                      "background-color: rgba(56,57,60);\n"
                                      "}")
        self.scriptPage.setObjectName("scriptPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scriptPage)
        self.verticalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.newPushButton = QtWidgets.QPushButton(self.scriptPage)
        self.newPushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.newPushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.newPushButton.setObjectName("newPushButton")
        self.verticalLayout_4.addWidget(self.newPushButton)
        self.runPushButton = QtWidgets.QPushButton(self.scriptPage)
        self.runPushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.runPushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.runPushButton.setObjectName("runPushButton")
        self.verticalLayout_4.addWidget(self.runPushButton)
        self.toolBox.addItem(self.scriptPage, "")
        self.aiPage = QtWidgets.QWidget()
        self.aiPage.setGeometry(QtCore.QRect(0, 0, 132, 84))
        self.aiPage.setStyleSheet("#aiPage{\n"
                                  "background-color: rgba(56,57,60);\n"
                                  "}")
        self.aiPage.setObjectName("aiPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.aiPage)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.picPushButton = QtWidgets.QPushButton(self.aiPage)
        self.picPushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.picPushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.picPushButton.setObjectName("picPushButton")
        self.verticalLayout_3.addWidget(self.picPushButton)
        self.textPushButton = QtWidgets.QPushButton(self.aiPage)
        self.textPushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.textPushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textPushButton.setObjectName("textPushButton")
        self.verticalLayout_3.addWidget(self.textPushButton)
        self.toolBox.addItem(self.aiPage, "")
        self.verticalLayout_2.addWidget(self.toolBox, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_4.addWidget(self.leftFrame)
        self.workFrame = QtWidgets.QFrame(self.bodyFrame)
        self.workFrame.setStyleSheet("QFrame#workFrame{\n"
                                     "background-color: rgba(245,245,245);\n"
                                     "border-bottom-right-radius:30px;\n"
                                     "}")
        self.workFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.workFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.workFrame.setObjectName("workFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.workFrame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.workFrame)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.workFrame)
        self.horizontalLayout_2.addWidget(self.bodyFrame)
        self.verticalLayout.addWidget(self.centerFrame)
        self.verticalLayout_5.addWidget(self.mainFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "自动办公助手"))
        self.newPushButton.setText(_translate("MainWindow", "新建脚本"))
        self.runPushButton.setText(_translate("MainWindow", "运行脚本"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.scriptPage), _translate("MainWindow", " 我的脚本"))
        self.picPushButton.setText(_translate("MainWindow", "图像识别"))
        self.textPushButton.setText(_translate("MainWindow", "文字识别"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.aiPage), _translate("MainWindow", " AI工具"))
