# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rpcServeWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rpcServeWidget(object):
    def setupUi(self, rpcServeWidget):
        rpcServeWidget.setObjectName("rpcServeWidget")
        rpcServeWidget.resize(325, 235)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(rpcServeWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rpcServeFrame = QtWidgets.QFrame(rpcServeWidget)
        self.rpcServeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rpcServeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rpcServeFrame.setObjectName("rpcServeFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rpcServeFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.rpcServeFrame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.ipLabe = QtWidgets.QLabel(self.groupBox)
        self.ipLabe.setObjectName("ipLabe")
        self.gridLayout.addWidget(self.ipLabe, 0, 0, 1, 1)
        self.ipLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ipLineEdit.setObjectName("ipLineEdit")
        self.gridLayout.addWidget(self.ipLineEdit, 0, 1, 1, 1)
        self.portLabel = QtWidgets.QLabel(self.groupBox)
        self.portLabel.setObjectName("portLabel")
        self.gridLayout.addWidget(self.portLabel, 1, 0, 1, 1)
        self.portLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.portLineEdit.setObjectName("portLineEdit")
        self.gridLayout.addWidget(self.portLineEdit, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.rpcServeFrame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runRpcButton = QtWidgets.QPushButton(self.groupBox_2)
        self.runRpcButton.setObjectName("runRpcButton")
        self.horizontalLayout.addWidget(self.runRpcButton)
        self.stopRpcButton = QtWidgets.QPushButton(self.groupBox_2)
        self.stopRpcButton.setObjectName("stopRpcButton")
        self.horizontalLayout.addWidget(self.stopRpcButton)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.rpcServeFrame)

        self.retranslateUi(rpcServeWidget)
        QtCore.QMetaObject.connectSlotsByName(rpcServeWidget)

    def retranslateUi(self, rpcServeWidget):
        _translate = QtCore.QCoreApplication.translate
        rpcServeWidget.setWindowTitle(_translate("rpcServeWidget", "RPC服务"))
        self.groupBox.setTitle(_translate("rpcServeWidget", "设置"))
        self.ipLabe.setText(_translate("rpcServeWidget", "本机IP"))
        self.portLabel.setText(_translate("rpcServeWidget", "端口号"))
        self.groupBox_2.setTitle(_translate("rpcServeWidget", "操作"))
        self.runRpcButton.setText(_translate("rpcServeWidget", "启动服务"))
        self.stopRpcButton.setText(_translate("rpcServeWidget", "停止服务"))
