# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textRegWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_textRegWidget(object):
    def setupUi(self, textRegWidget):
        textRegWidget.setObjectName("textRegWidget")
        textRegWidget.resize(660, 790)
        self.horizontalLayout = QtWidgets.QHBoxLayout(textRegWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(57, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.textRegFrame = QtWidgets.QFrame(textRegWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textRegFrame.sizePolicy().hasHeightForWidth())
        self.textRegFrame.setSizePolicy(sizePolicy)
        self.textRegFrame.setMinimumSize(QtCore.QSize(500, 0))
        self.textRegFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textRegFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textRegFrame.setObjectName("textRegFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.textRegFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.textRegFrame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.serveLabel = QtWidgets.QLabel(self.groupBox)
        self.serveLabel.setObjectName("serveLabel")
        self.gridLayout.addWidget(self.serveLabel, 0, 0, 1, 1)
        self.serveLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.serveLineEdit.setObjectName("serveLineEdit")
        self.gridLayout.addWidget(self.serveLineEdit, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.textRegFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pictureLabel = QtWidgets.QLabel(self.groupBox_3)
        self.pictureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pictureLabel.setObjectName("pictureLabel")
        self.verticalLayout_2.addWidget(self.pictureLabel)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.textRegFrame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout.addWidget(self.textRegFrame)
        spacerItem1 = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(textRegWidget)
        QtCore.QMetaObject.connectSlotsByName(textRegWidget)

    def retranslateUi(self, textRegWidget):
        _translate = QtCore.QCoreApplication.translate
        textRegWidget.setWindowTitle(_translate("textRegWidget", "Form"))
        self.groupBox.setTitle(_translate("textRegWidget", "识别设置"))
        self.serveLabel.setText(_translate("textRegWidget", "识别服务"))
        self.groupBox_3.setTitle(_translate("textRegWidget", "添加图片"))
        self.pictureLabel.setText(_translate("textRegWidget", "在此拖入图片"))
        self.groupBox_2.setTitle(_translate("textRegWidget", "识别结果"))
